import { cn } from "@/utils/cn";
import "./globals.css";
import { Inter } from "next/font/google";
import MoreMenu from "@/components/template/more-menu";
import UserMenu from "@/components/template/user-menu";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import SettingIcon from "@/components/icons/setting-icon";
import HelpIcon from "@/components/icons/help-icon";
import SearchMenu from "@/components/template/search-menu";
import SideMenu from "@/components/template/side-menu";
import EmailList from "@/components/template/email-list";
import { Dialog } from "@/components/ui/dialog";
import { Command, CommandGroup } from "@/components/ui/command";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kmail ",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }) {
  // console.log(fakeData)

  return (
    <html lang="en">
      <body className={cn(inter.className, "")}>
        <Dialog>
          <div className="bg-zinc-950 z-0  relative flex flex-row h-screen overflow-y-hidden ">
            <SideMenu />
            <div className="h-full w-full flex relative flex-col">
              <Command>
                <header className="h-[60px] shrink-0 flex items-center justify-between px-8 border-b border-zinc-800  top-0 bg-neutral-900 w-full">
                  <SearchMenu />

                  <div className="flex gap-2 justify-self-end">
                    <TooltipProvider>
                      <Tooltip>
                        <TooltipTrigger>
                          <HelpIcon className=" hidden lg:block p-px cursor-pointer rounded text-green-600 hover:text-green-300" />
                        </TooltipTrigger>
                        <TooltipContent className="text-xs bg-gray-700/50 border-none text-white">
                          <p>ask or help</p>
                        </TooltipContent>
                      </Tooltip>
                    </TooltipProvider>
                    <TooltipProvider>
                      <Tooltip>
                        <TooltipTrigger>
                          <SettingIcon className=" hidden lg:block p-px cursor-pointer rounded text-green-600 hover:text-green-300" />
                        </TooltipTrigger>
                        <TooltipContent className="text-xs bg-gray-700/50 border-none text-white">
                          <p>settings</p>
                        </TooltipContent>
                      </Tooltip>
                    </TooltipProvider>
                    <MoreMenu />
                    <UserMenu />
                  </div>
                </header>
                <div className="flex flex-row h-full relative w-full">
                  <EmailList />

                  {children}
                </div>
              </Command>
            </div>
          </div>
          {modal}
        </Dialog>
      </body>
    </html>
  );
}
