name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Repo Visualizer
        uses: githubocto/repo-visualizer@0.9.1
        with:
          excluded_paths: "ignore,.github,.vscode"
